spring:
  application:
    name: spring-config-server
  profiles:
    active:
      - dev
  cloud:
    config:
      server:
        vault:
          order: 1
        git:
          order: 2
          uri: https://github.com/jackhalfalltrades/service-properties
server:
  port: 7601
  ssl:
    enabled: false
logging:
  level:
    com.jackhalfalltrades.configServer.springConfigServer: debug
    org.springframework: debug