spring:
  application:
    name: spring-config-server
  profiles:
    active:
      - dev
server:
  port: 7601
  ssl:
    enabled: false
#    key-store: ${KEYSTORE_PATH}
#    key-store-password: ${KEYSTORE_PASSWD}

logging:
  level:
    com.jackhalfalltrades.configServer.springConfigServer: debug
    org.springframework: debug

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///Users/chandrakanthperavelli/Documents/workspace-java/service-properties/